-- FIXME: not working on second machine due to python failing to initialize
-- enhance wildmenu
-- local wilder = require("wilder")
-- wilder.setup({ modes = { ":" } })

-- local pipeline = {
-- 	wilder.branch(
-- 		wilder.python_file_finder_pipeline({
-- 			file_command = function(ctx, arg)
-- 				if string.find(arg, ".") ~= nil then
-- 					return { "rg", "--files", "--hidden" }
-- 				else
-- 					return { "rg", "--files" }
-- 				end
-- 			end,
-- 			dir_command = { "fd", "-td" },
-- 			filters = { "fruzzy_filter" },
-- 		}),
-- 		wilder.substitute_pipeline({
-- 			pipeline = wilder.python_search_pipeline({
-- 				skip_cmdtype_check = 1,
-- 				pattern = wilder.python_fuzzy_pattern({
-- 					start_at_boundary = 0,
-- 				}),
-- 			}),
-- 		}),
-- 		wilder.cmdline_pipeline({
-- 			fuzzy = 2,
-- 			fuzzy_filter = wilder.lua_fzy_filter(),
-- 		}),
-- 		{
-- 			wilder.check(function(_, x)
-- 				return x == ""
-- 			end),
-- 			wilder.history(),
-- 		},
-- 		wilder.python_search_pipeline({
-- 			pattern = wilder.python_fuzzy_pattern({
-- 				start_at_boundary = 0,
-- 			}),
-- 		})
-- 	),
-- }
-- wilder.set_option("pipeline", pipeline)

-- local popupmenu_renderer = wilder.popupmenu_renderer(wilder.popupmenu_border_theme({
-- 	border = "rounded",
-- 	highlighter = {
-- 		wilder.lua_fzy_highlighter(),
-- 		wilder.basic_highlighter(),
-- 	},
-- 	highlights = {
-- 		accent = wilder.make_hl("WilderAccent", "Pmenu", { { a = 1 }, { a = 1 }, { foreground = "#f4468f" } }),
-- 	},
-- 	left = {
-- 		" ",
-- 		wilder.popupmenu_devicons(),
-- 		wilder.popupmenu_buffer_flags({
-- 			flags = " a + ",
-- 			icons = { ["+"] = "", a = "", h = "" },
-- 		}),
-- 	},
-- 	right = {
-- 		" ",
-- 		wilder.popupmenu_scrollbar(),
-- 	},
-- }))

-- wilder.set_option("renderer", popupmenu_renderer)

